/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_media_codecs_ultrahdr_UltraHDRDecoder */

#ifndef _Included_com_google_media_codecs_ultrahdr_UltraHDRDecoder
#define _Included_com_google_media_codecs_ultrahdr_UltraHDRDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    isUHDRImageNative
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_isUHDRImageNative
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_init
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    setCompressedImageNative
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_setCompressedImageNative
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    setOutputFormatNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_setOutputFormatNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    setColorTransferNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_setColorTransferNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    setMaxDisplayBoostNative
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_setMaxDisplayBoostNative
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    enableGpuAccelerationNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_enableGpuAccelerationNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    probeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_probeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getImageWidthNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getImageWidthNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getImageHeightNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getImageHeightNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getGainMapWidthNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getGainMapWidthNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getGainMapHeightNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getGainMapHeightNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getExifNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getExifNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getIccNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getIccNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getBaseImageNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getBaseImageNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getGainMapImageNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getGainMapImageNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getGainmapMetadataNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getGainmapMetadataNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    decodeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_decodeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getDecodedImageNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getDecodedImageNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    getDecodedGainMapImageNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_getDecodedGainMapImageNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDRDecoder
 * Method:    resetNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDRDecoder_resetNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
