/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_media_codecs_ultrahdr_UltraHDREncoder */

#ifndef _Included_com_google_media_codecs_ultrahdr_UltraHDREncoder
#define _Included_com_google_media_codecs_ultrahdr_UltraHDREncoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_CODEC_JPG
#define com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_CODEC_JPG 0L
#undef com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_CODEC_HEIF
#define com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_CODEC_HEIF 1L
#undef com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_CODEC_AVIF
#define com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_CODEC_AVIF 2L
#undef com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_USAGE_REALTIME
#define com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_USAGE_REALTIME 0L
#undef com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_USAGE_BEST_QUALITY
#define com_google_media_codecs_ultrahdr_UltraHDREncoder_UHDR_USAGE_BEST_QUALITY 1L
/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_init
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setRawImageNative
 * Signature: ([IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setRawImageNative___3IIIIIIIII
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setRawImageNative
 * Signature: ([JIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setRawImageNative___3JIIIIIIII
  (JNIEnv *, jobject, jlongArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setRawImageNative
 * Signature: ([S[SIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setRawImageNative___3S_3SIIIIIIIII
  (JNIEnv *, jobject, jshortArray, jshortArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setRawImageNative
 * Signature: ([B[B[BIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setRawImageNative___3B_3B_3BIIIIIIIIII
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setCompressedImageNative
 * Signature: ([BIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setCompressedImageNative
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setGainMapImageInfoNative
 * Signature: ([BI[F[F[F[F[FFFZ)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setGainMapImageInfoNative
  (JNIEnv *, jobject, jbyteArray, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloat, jfloat, jboolean);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setExifDataNative
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setExifDataNative
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setQualityFactorNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setQualityFactorNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setMultiChannelGainMapEncodingNative
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setMultiChannelGainMapEncodingNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setGainMapScaleFactorNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setGainMapScaleFactorNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setGainMapGammaNative
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setGainMapGammaNative
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setEncPresetNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setEncPresetNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setOutputFormatNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setOutputFormatNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setMinMaxContentBoostNative
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setMinMaxContentBoostNative
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    setTargetDisplayPeakBrightnessNative
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_setTargetDisplayPeakBrightnessNative
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    encodeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_encodeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    getOutputNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_getOutputNative
  (JNIEnv *, jobject);

/*
 * Class:     com_google_media_codecs_ultrahdr_UltraHDREncoder
 * Method:    resetNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_media_codecs_ultrahdr_UltraHDREncoder_resetNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
